/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pac_man;

import com.bridge.Game;
import com.bridge.core.exceptions.GameException;
import com.bridge.gamesettings.AGameSettings;
import com.bridge.initializerhandler.GameInitializer;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        GameInitializer gameInitializer = new GameInitializer();
        Game game = new Game(new AGameSettings() {
            @Override
            public boolean isGameOver() {
                return false;
            }
        });

        PacManGameInitializer pacmanGame = new PacManGameInitializer(game);
        gameInitializer.subscribe(pacmanGame);

        try {
            game.run();
        } catch (GameException e) {
            e.printStackTrace();
        }
    }
}
