/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pac_man;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        GameInitializer gameInitializer = new GameInitializer();
        gameInitializer.init();
    }
}
