/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pac_man;

import com.bridge.Game;
import com.bridge.core.exceptions.GameException;
import com.bridge.core.exceptions.initializerhandler.NotPossibleToInitializeSubscribersException;
import com.bridge.gamesettings.AGameSettings;
import com.bridge.initializerhandler.GameInitializer;
import com.bridge.processinputhandler.InputVerifier;
import com.bridge.processinputhandler.KeyboardEventManager;
import com.bridge.renderHandler.render.RenderManager;
import com.pac_man.characters.Ghost.Ghost;
import com.pac_man.characters.Pacman.Pacman;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        GameInitializer pacManGameInitializer = new GameInitializer();


        PacManGameInitializer pacmanGame = new PacManGameInitializer();
        pacManGameInitializer.subscribe(pacmanGame);
        try {
            pacManGameInitializer.initializeSubscribers();
        } catch (NotPossibleToInitializeSubscribersException e) {
            throw new RuntimeException(e);
        }



        Game game = new Game(
                new InputVerifier(List.of(pacmanGame.getKeyboardEventManager())),
                new AGameSettings() {
                    @Override
                    public boolean isGameOver() {
                        return false;
                    }
                },
                pacmanGame.getUpdatePublisher(),
                new RenderManager(null, null),
                pacManGameInitializer

        );

        try {
            game.run();
        } catch (GameException e) {
            throw new RuntimeException(e);
        }


    }
}
